#!/bin/bash

calcjar=/Users/guy/Library/lib/kc.jar
classpath=/Users/guy/Library/lib/kotlin-runner.jar:/Users/guy/Library/lib/jline-3.25.2-SNAPSHOT.jar:$calcjar
mainclass=com.guy.calc.MainKt

java -cp $classpath $mainclass